use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Game {
    pub id: Option<i64>,
    pub title: String,
    pub sort_title: Option<String>,
    pub platform: String,
    pub developer: Option<String>,
    pub publisher: Option<String>,
    pub release_date: Option<String>,
    pub year: Option<i32>,
    pub genre: Option<String>,
    pub series: Option<String>,
    pub play_mode: Option<String>,
    pub rating: Option<f64>,
    pub description: Option<String>,
    pub notes: Option<String>,
    pub source: Option<String>,
    pub application_path: Option<String>,
    pub dosbox_conf: Option<String>,
    pub status: Option<String>,
    pub region: Option<String>,
    pub max_players: Option<i32>,
    pub language: String,
    pub shortcode: Option<String>,
    pub available_languages: Option<String>,
    pub torrent_source: Option<String>,
    pub in_library: bool,
    pub installed: bool,
    pub favorited: bool,
    pub game_torrent_index: Option<i64>,
    pub gamedata_torrent_index: Option<i64>,
    pub download_size: Option<i64>,
    pub has_thumbnail: bool,
    pub dosbox_variant: Option<String>,
}
